# Generated by Django 6.0.2 on 2026-02-15 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_account_category_subcategory_transaction_expense"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Conta", "verbose_name_plural": "Contas"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "Despesa", "verbose_name_plural": "Despesas"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"verbose_name": "Subcategoria", "verbose_name_plural": "Subcategorias"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Transação", "verbose_name_plural": "Transações"},
        ),
        migrations.CreateModel(
            name="TransactionSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendente"), ("ACCEPTED", "Aceito"), ("REJECTED", "Rejeitado"), ("EDITED", "Editado")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.category")),
                (
                    "subcategory",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.subcategory"),
                ),
                (
                    "transaction",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="suggestion", to="core.transaction"),
                ),
            ],
            options={
                "verbose_name": "Sugestão de Transação",
                "verbose_name_plural": "Sugestões de Transação",
            },
        ),
    ]
